### ISSUE TITLE
Tests failing on the nightlies

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.bio.base#23]
This package is failing on all our Python 3.4 builds with the following error:

```text
======================================================================
ERROR: bob.bio.base.test.test_scripts.test_resources
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/buildbot/work/gitlab-ci/work/gitlab-ci/f6f95b82/1/biometric/bob.nightlies/layers/2/bob.bio.base/bob/bio/base/test/test_scripts.py", line 373, in test_resources
    databases([])
  File "/Users/buildbot/work/gitlab-ci/work/gitlab-ci/f6f95b82/1/biometric/bob.nightlies/layers/2/bob.bio.base/bob/bio/base/script/resources.py", line 60, in databases
    databases = bob.bio.base.utils.resources.database_directories(replacements=args.database_directories_file)
  File "/Users/buildbot/work/gitlab-ci/work/gitlab-ci/f6f95b82/1/biometric/bob.nightlies/layers/2/bob.bio.base/bob/bio/base/utils/resources.py", line 227, in database_directories
    for entry_point in sorted(entry_points):
nose.proxy.TypeError: unorderable types: EntryPoint() < EntryPoint()
-------------------- >> begin captured logging << --------------------
```

Ref: https://gitlab.idiap.ch/biometric/bob.nightlies/builds/3106

Not sure how to change this one. Could you please check?

**Comment by tiagofrepereira2012** [comment]
I can have a look on it

**Comment by tiagofrepereira2012** [comment]
Well, basically the error is obvious, since you cannot compare EntryPoint objects you can not sort them via `sorted` function.

What is strange is why this works on python3 on travis and why this not work on python3 in our nightlies (and in my workstation)?
All of them were bootstraped with `setuptools==22.0.5`, so the `EntryPoint` object is the same for all builds.

**Comment by siebenkopf** [comment]
I don't know, why this happens, especially since it passes in the Travis Python 3.4 builds.

However, one solution would be to define a key in the sorted function:
https://wiki.python.org/moin/HowTo/Sorting
I am currently not at work, so I would have to search, which is the correct key to be used. I can do that later, this should not be very difficult.

**Comment by tiagofrepereira2012** [comment]
I can solve this via lambda functions.
This does the job
```
sorted(entry_points, key=lambda entry_point: entry_point.name)
```

Will do a pull request

**Comment by tiagofrepereira2012** [comment]
Now is failing with the in bob.db.verification.utils https://github.com/bioidiap/bob.db.verification.utils/blob/master/bob/db/verification/utils/database.py#L410.

The exception is raised by SQLAlchemy.
```
Exception ignored in: <bound method Database.__del__ of <bob.db.multipie.query.Database object at 0x7f5b00bda320>>
Traceback (most recent call last):
  File "/local/scratch/tpereira/github/tiagofrepereira2012/bob.bio.base/src/bob.db.verification.utils/bob/db/verification/utils/database.py", line 410, in __del__
  File "/idiap/group/torch5spro/releases/bob-stable/py34/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1838, in dispose
  File "/idiap/group/torch5spro/releases/bob-stable/py34/lib/python3.4/site-packages/sqlalchemy/pool.py", line 1163, in recreate
  File "/idiap/group/torch5spro/releases/bob-stable/py34/lib/python3.4/site-packages/sqlalchemy/pool.py", line 239, in __init__
  File "/idiap/group/torch5spro/releases/bob-stable/py34/lib/python3.4/site-packages/sqlalchemy/event/base.py", line 142, in _update
  File "/idiap/group/torch5spro/releases/bob-stable/py34/lib/python3.4/site-packages/sqlalchemy/event/attr.py", line 319, in _update
  File "/idiap/group/torch5spro/releases/bob-stable/py34/lib/python3.4/site-packages/sqlalchemy/event/registry.py", line 113, in _stored_in_collection_multi
KeyError: <weakref at 0x7f5b00c0def8; to 'function' at 0x7f5b006f48c8 (go)>
```

The versions of SQLAlchemy on `py34-ubuntu-latest` and on Travis are the same (1.0.13).

**Comment by tiagofrepereira2012** [comment]
I didn't realized that the exception was ignored.
I will close this one

**Comment by siebenkopf** [comment]
Anyways, this exception should be caught and do not get through. As you can see in the code that you have pointed out, I am already catching ``TypeError`` and ``AttributeError``, but apparently not the ``KeyError`` that is actually raised. I will correct that.
